# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/CLRX_system_ila_3_0.xci
# IP: The module: 'CLRX_system_ila_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/bd_6224.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6224 || ORIG_REF_NAME==bd_6224} -quiet] -quiet

# IP: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/bd_6224_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6224_ila_lib_0 || ORIG_REF_NAME==bd_6224_ila_lib_0} -quiet] -quiet

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6224_ila_lib_0 || ORIG_REF_NAME==bd_6224_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6224_ila_lib_0 || ORIG_REF_NAME==bd_6224_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/bd_6224_ila_lib_0_ooc.xdc

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/bd_6224_ooc.xdc

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/CLRX_system_ila_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLRX_system_ila_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/CLRX_system_ila_3_0.xci
# IP: The module: 'CLRX_system_ila_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/bd_6224.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6224 || ORIG_REF_NAME==bd_6224} -quiet] -quiet

# IP: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/bd_6224_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6224_ila_lib_0 || ORIG_REF_NAME==bd_6224_ila_lib_0} -quiet] -quiet

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6224_ila_lib_0 || ORIG_REF_NAME==bd_6224_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6224_ila_lib_0 || ORIG_REF_NAME==bd_6224_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/ip/ip_0/bd_6224_ila_lib_0_ooc.xdc

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/bd_0/bd_6224_ooc.xdc

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_system_ila_3_0/CLRX_system_ila_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLRX_system_ila_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
