# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/scripts/7series_iWave_yv_cl_io.xdc

# Block Designs: bd/CLRX/CLRX.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX || ORIG_REF_NAME==CLRX} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_YV_CL_RX_TOP_0_0/CLRX_YV_CL_RX_TOP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_YV_CL_RX_TOP_0_0 || ORIG_REF_NAME==CLRX_YV_CL_RX_TOP_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_YV_OBUFDS_1_0/CLRX_YV_OBUFDS_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_YV_OBUFDS_1_0 || ORIG_REF_NAME==CLRX_YV_OBUFDS_1_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_axi_dma_1_0/CLRX_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_axi_dma_1_0 || ORIG_REF_NAME==CLRX_axi_dma_1_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_axi_gpio_0_0/CLRX_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_axi_gpio_0_0 || ORIG_REF_NAME==CLRX_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_s00_regslice_0/CLRX_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_s00_regslice_0 || ORIG_REF_NAME==CLRX_s00_regslice_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_s00_data_fifo_0/CLRX_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_s00_data_fifo_0 || ORIG_REF_NAME==CLRX_s00_data_fifo_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_0/CLRX_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_0 || ORIG_REF_NAME==CLRX_auto_pc_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_axi_interconnect_0_0/CLRX_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_axi_interconnect_0_0 || ORIG_REF_NAME==CLRX_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_axi_uart16550_1_0/CLRX_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_axi_uart16550_1_0 || ORIG_REF_NAME==CLRX_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_axis_data_fifo_0_0/CLRX_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_axis_data_fifo_0_0 || ORIG_REF_NAME==CLRX_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_clk_wiz_0_0/CLRX_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_clk_wiz_0_0 || ORIG_REF_NAME==CLRX_clk_wiz_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_clk_wiz_1_0/CLRX_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_clk_wiz_1_0 || ORIG_REF_NAME==CLRX_clk_wiz_1_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_data_mux_0_0/CLRX_data_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_data_mux_0_0 || ORIG_REF_NAME==CLRX_data_mux_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_proc_sys_reset_0_0/CLRX_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_proc_sys_reset_0_0 || ORIG_REF_NAME==CLRX_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_processing_system7_0_0/CLRX_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_processing_system7_0_0 || ORIG_REF_NAME==CLRX_processing_system7_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_xbar_0/CLRX_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_xbar_0 || ORIG_REF_NAME==CLRX_xbar_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_7/CLRX_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_7 || ORIG_REF_NAME==CLRX_auto_pc_7} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_1/CLRX_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_1 || ORIG_REF_NAME==CLRX_auto_pc_1} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_2/CLRX_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_2 || ORIG_REF_NAME==CLRX_auto_pc_2} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_3/CLRX_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_3 || ORIG_REF_NAME==CLRX_auto_pc_3} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_4/CLRX_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_4 || ORIG_REF_NAME==CLRX_auto_pc_4} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_5/CLRX_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_5 || ORIG_REF_NAME==CLRX_auto_pc_5} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_auto_pc_6/CLRX_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_auto_pc_6 || ORIG_REF_NAME==CLRX_auto_pc_6} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_ps7_0_axi_periph_0/CLRX_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_ps7_0_axi_periph_0 || ORIG_REF_NAME==CLRX_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_system_ila_3_0/CLRX_system_ila_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_system_ila_3_0 || ORIG_REF_NAME==CLRX_system_ila_3_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_util_ds_buf_2_0/CLRX_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_util_ds_buf_2_0 || ORIG_REF_NAME==CLRX_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_xlconcat_2_0/CLRX_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_xlconcat_2_0 || ORIG_REF_NAME==CLRX_xlconcat_2_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_xlconcat_3_0/CLRX_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_xlconcat_3_0 || ORIG_REF_NAME==CLRX_xlconcat_3_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_xlconstant_0_0/CLRX_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_xlconstant_0_0 || ORIG_REF_NAME==CLRX_xlconstant_0_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_xlconstant_1_0/CLRX_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_xlconstant_1_0 || ORIG_REF_NAME==CLRX_xlconstant_1_0} -quiet] -quiet

# IP: bd/CLRX/ip/CLRX_xlslice_0_0/CLRX_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CLRX_xlslice_0_0 || ORIG_REF_NAME==CLRX_xlslice_0_0} -quiet] -quiet

# XDC: bd/CLRX/CLRX_ooc.xdc
