# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_auto_pc_6/CLRX_auto_pc_6.xci
# IP: The module: 'CLRX_auto_pc_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_auto_pc_6/CLRX_auto_pc_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLRX_auto_pc_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_auto_pc_6/CLRX_auto_pc_6.xci
# IP: The module: 'CLRX_auto_pc_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bipin/CameraLink_hash/DEV/7series/RX_Project/project/cl_rx_7series_iWave_yv_iWave_cl_2019.2/cl_rx_7series_iWave_yv_iWave_cl_2019.2.srcs/sources_1/bd/CLRX/ip/CLRX_auto_pc_6/CLRX_auto_pc_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLRX_auto_pc_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
